### ISSUE TITLE
Can't see any available servers after installing deb file on xubuntu 18.04

### ISSUE THREAD

**Issue by Motherboard** [rarcher/couch-potato-server#29]
It says it installed correctly, I've restarted the system, but I don't see any servers on the android client.

**Comment by rarcher** [comment]
This could be related to your network configuration.  Have you tried pinging your PC from your Android device? (There are multiple apps that will let you do this.)  Also, the server and PC need to be on the same IP subnet for the scan to work.

**Comment by rarcher** [comment]
@Motherboard I just uploaded a new version of the client with an option to enter a server IP address manually.  Are you able to connect using that method?
